-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 08:12:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atividadesifba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividadesifba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividadesifba` DEFAULT CHARACTER SET utf8 ;
USE `atividadesifba` ;

-- -----------------------------------------------------
-- Table `atividadesifba`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividadesifba`.`turmas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividadesifba`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividadesifba`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` INT NULL,
  `foto` VARCHAR(150) NULL,
  `turmas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `turmas_id`),
  INDEX `fk_usuarios_turmas1_idx` (`turmas_id` ASC),
  CONSTRAINT `fk_usuarios_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `atividadesifba`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividadesifba`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividadesifba`.`disciplinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividadesifba`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividadesifba`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `descricao` TEXT NULL,
  `data` DATE NULL,
  `turmas_id` INT NOT NULL,
  `disciplinas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `turmas_id`, `disciplinas_id`),
  INDEX `fk_atividades_turmas_idx` (`turmas_id` ASC),
  INDEX `fk_atividades_disciplinas1_idx` (`disciplinas_id` ASC),
  CONSTRAINT `fk_atividades_turmas`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `atividadesifba`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_disciplinas1`
    FOREIGN KEY (`disciplinas_id`)
    REFERENCES `atividadesifba`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
